# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: serverless

plugins:
  - serverless-python-requirements

# DRY constants: define all compound/generated names in one place
# Override args are: .. defaults:
# --app_acroym          signed-uploader
# --s3_bucket           self:custom.app_acronym
# --s3_key_base         self:custom.stage
# --region              us-east-1
# --stage               test
# --deletion_policy     delete

custom:
  app_acronym: wibble-foo
  default_stage: test

  stage: ${opt:branch}
  stack_name: ${self:custom.stage}-${self:custom.app_acronym}
  region: ${opt:region, self:provider.region}
  deletion_policy: Delete
  # Default to using app_acronym as bucket name
  s3_bucket: ${opt:s3_bucket, self:custom.app_acronym}
  # default to using ${stage} as key base path, keeps stages from namespace collisions
  s3_key_base: ${opt:s3_key_base, self:custom.stage}
  s3_bucket_arn: arn:aws:s3:::${self:custom.s3_bucket}
  s3_role_resource: ${self:custom.s3_bucket_arn}/${self:custom.s3_key_base}/*
  # Put this here rather than in code (presigned URL TTL)
  url_default_ttl: 60


# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: python3.8
  region: eu-west-1
  environment:
    S3_BUCKET: ${self:custom.s3_bucket}
    S3_KEY_BASE: ${self:custom.s3_key_base}
    URL_DEFAULT_TTL: ${self:custom.url_default_ttl}


# The `functions` block defines what code to deploy
functions:
  helloWorld:
    name: ${self:custom.stack_name}-hello-world
    handler: handler.run
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      # Invoke Lambda function every minute
      - schedule: cron(0 * * * ? *)
    iamRoleStatementsName: $${self:custom.stack_name}-role-lambda
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:*
        Resource: ${self:custom.s3_role_resource}
