# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: serverless

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: python3.6
  region: eu-west-1

# The `functions` block defines what code to deploy
functions:
  helloWorld:
    handler: handler.run
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      # Invoke Lambda function every minute
      - schedule: rate(1 minute)
