on:
  push:

name: Deploy master branch

jobs:

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=git-branch;]$(echo ${GITHUB_REF##*/})"
      id: extract_branch
  
    - name: serverless deploy
      uses: mooperd/serverless-github-action@master
      with:
        args: deploy --git-branch=${{ steps.extract_branch.outputs.git-branch }} --git-sha=$GITHUB_SHA
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}