on:
  push:
    branches:
      - master

name: Deploy master branch


jobs:
  run-env:
    name: Run Env
    runs-on: ubuntu-latest
    steps:
    - name: Env
      run: env

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: npm install
      uses: actions/setup-node@master
      with:
        args: install
    
    - name: serverless deploy
      uses: mooperd/serverless-github-action@master
      with:
        args: deploy --stage=${GITHUB_REF##*/}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}