on:
  push:

name: Deploy master branch

jobs:

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
      id: extract_branch

    - name: Checkout
      uses: actions/checkout@master
    
    - name: git location file
      shell: bash
      run: $(git rev-parse --short "$GITHUB_SHA")-${GITHUB_REF##*/} > git-location.txt
    
    - name: serverless deploy
      uses: mooperd/serverless-github-action@master
      with:
        args: deploy --branch=${{ steps.extract_branch.outputs.branch }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}